name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y binutils cmake dpkg-dev g++ gcc libssl-dev git \
          libx11-dev libxext-dev libxft-dev libxpm-dev python3 libtbb-dev libvdt-dev libgif-dev

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: root --version
